server:
  appVersion: "1.0.0"
  host: "0.0.0.0"
  port: "3048"
  mode: "PROD"
  readTimeout: 5
  writeTimeout: 5
  maxHeaderBytes: 10
  ctxTimeout: 4

logger:
  development: true
  encoding: json
  level: info
  indexName: "address_log"
  elasticSearchUrl: http://elasticsearch:9200

metric:
  url: localhost:3000
  serviceName: address_api

auth:
  jwtSecret: "your_secret_key"

redis:
  addr: "localhost:6379"

kafka:
  brokers:
    - "kafka:9092"
  consumerGroup: "address-service-group"
  maxPollRecords: 100
  groupId: "address-consumer-group"
  autoCommit: true
  fetchMaxWaitMs: 500

postgres:
  host: api_postgresql
  port: 5432
  username: pg
  password: admin
  dbname: address_db
  sslMode: false
  driver: pgx
  maxOpenConnections: 60
  connMaxLifeTime: 120
  maxIdleConnections: 30
  connMaxIdleTime: 20