server:
  appVersion: "1.0.0"
  host: "localhost"
  port: "3048"
  mode: "Dev"
  readTimeout: 5
  writeTimeout: 5
  maxHeaderBytes: 10
  ctxTimeout: 4

logger:
  development: true
  encoding: json
  level: info
  indexName: "address_log"
  elasticSearchUrl: http://localhost:9200

kafka:
  brokers:
    - "0.0.0.0:9092"
  consumerGroup: "address-service-group"
  maxPollRecords: 100
  groupId: "address-consumer-group"
  autoCommit: true
  fetchMaxWaitMs: 500

metric:
  url: localhost:3000
  serviceName: address_api

auth:
  jwtSecret: "your_secret_key"

postgres:
  host: localhost
  port: 5432
  username: pg
  password: admin
  dbname: address_db
  sslMode: false
  driver: pgx
  maxOpenConnections: 60
  connMaxLifeTime: 120
  maxIdleConnections: 30
  connMaxIdleTime: 20