global:
  # How frequently to scrape targets
  scrape_interval:     10s
  # How frequently to evaluate rules
  evaluation_interval: 10s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: [ 'prometheus_container:9090' ]
  - job_name: 'address_api'
    scrape_interval: 5s
    static_configs:
      - targets:
          - "address-api:3048"